"""Cele 50 riscuri structurale - biblioteca platformei."""

RISKS_50 = [
    # 1. Riscuri informaționale (R1-R6)
    {
        "code": "R1",
        "category": "informational",
        "name": "Documente incomplete",
        "impact": 3,
        "probability": 2,
    },
    {
        "code": "R2",
        "category": "informational",
        "name": "Documente transmise cu întârziere",
        "impact": 3,
        "probability": 2,
    },
    {
        "code": "R3",
        "category": "informational",
        "name": "Lipsa explicației economice a tranzacției",
        "impact": 3,
        "probability": 2,
    },
    {
        "code": "R4",
        "category": "informational",
        "name": "Informații contradictorii",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R5",
        "category": "informational",
        "name": "Lipsa comunicării tranzacțiilor relevante",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R6",
        "category": "informational",
        "name": "Lipsa documentelor justificative suport",
        "impact": 4,
        "probability": 2,
    },
    # 2. Riscuri tranzacționale (R7-R12)
    {
        "code": "R7",
        "category": "transactional",
        "name": "Volum ridicat de tranzacții",
        "impact": 2,
        "probability": 2,
    },
    {
        "code": "R8",
        "category": "transactional",
        "name": "Tranzacții repetitive cu impact fiscal",
        "impact": 3,
        "probability": 2,
    },
    {
        "code": "R9",
        "category": "transactional",
        "name": "Tranzacții intracomunitare",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R10",
        "category": "transactional",
        "name": "Tranzacții internaționale extra UE",
        "impact": 5,
        "probability": 2,
    },
    {
        "code": "R11",
        "category": "transactional",
        "name": "Tranzacții neobișnuite sau atipice",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R12",
        "category": "transactional",
        "name": "Tranzacții frecvente în numerar",
        "impact": 4,
        "probability": 2,
    },
    # 3. Riscuri fiscale (R13-R21)
    {
        "code": "R13",
        "category": "fiscal",
        "name": "Tratament TVA incorect",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R14",
        "category": "fiscal",
        "name": "Tranzacții economice complexe",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R15",
        "category": "fiscal",
        "name": "Tratament TVA incert",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R16",
        "category": "fiscal",
        "name": "Deduceri fiscale incorect aplicate",
        "impact": 5,
        "probability": 2,
    },
    {
        "code": "R17",
        "category": "fiscal",
        "name": "Venituri necorelate fiscal",
        "impact": 5,
        "probability": 2,
    },
    {
        "code": "R18",
        "category": "fiscal",
        "name": "Cheltuieli cu deductibilitate incertă",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R19",
        "category": "fiscal",
        "name": "Aplicare eronată tratament fiscal",
        "impact": 5,
        "probability": 2,
    },
    {
        "code": "R20",
        "category": "fiscal",
        "name": "Diferențe între evidența fiscală și contabilă",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R21",
        "category": "fiscal",
        "name": "Aplicare incorectă facilități fiscale",
        "impact": 5,
        "probability": 2,
    },
    # 4. Riscuri contabile (R22-R27)
    {
        "code": "R22",
        "category": "accounting",
        "name": "Politici contabile neclare",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R23",
        "category": "accounting",
        "name": "Înregistrări contabile întârziate",
        "impact": 3,
        "probability": 2,
    },
    {
        "code": "R24",
        "category": "accounting",
        "name": "Clasificare contabilă eronată",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R25",
        "category": "accounting",
        "name": "Neconcordanțe între evidențe",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R26",
        "category": "accounting",
        "name": "Lipsa documentării tratamentelor contabile",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R27",
        "category": "accounting",
        "name": "Sisteme contabile necorelate",
        "impact": 4,
        "probability": 2,
    },
    # 5. Riscuri operaționale (R28-R32)
    {
        "code": "R28",
        "category": "operational",
        "name": "Lipsa procedurilor interne",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R29",
        "category": "operational",
        "name": "Lipsa controlului asupra documentelor",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R30",
        "category": "operational",
        "name": "Control intern insuficient",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R31",
        "category": "operational",
        "name": "Flux informațional neclar",
        "impact": 3,
        "probability": 2,
    },
    {
        "code": "R32",
        "category": "operational",
        "name": "Lipsa responsabilului pentru comunicarea cu contabilul",
        "impact": 4,
        "probability": 2,
    },
    # 6. Riscuri juridice (R33-R37)
    {
        "code": "R33",
        "category": "legal",
        "name": "Contracte neclare",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R34",
        "category": "legal",
        "name": "Tranzacții fără contract",
        "impact": 5,
        "probability": 2,
    },
    {
        "code": "R35",
        "category": "legal",
        "name": "Contracte incomplete",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R36",
        "category": "legal",
        "name": "Clauze contractuale insuficiente",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R37",
        "category": "legal",
        "name": "Litigii comerciale",
        "impact": 5,
        "probability": 2,
    },
    # 7. Riscuri de conformare (R38-R43)
    {
        "code": "R38",
        "category": "compliance",
        "name": "Nerespectarea obligațiilor declarative",
        "impact": 5,
        "probability": 2,
    },
    {
        "code": "R39",
        "category": "compliance",
        "name": "Nerespectarea obligațiilor fiscale",
        "impact": 5,
        "probability": 2,
    },
    {
        "code": "R40",
        "category": "compliance",
        "name": "Nerespectarea termenelor legale",
        "impact": 5,
        "probability": 2,
    },
    {
        "code": "R41",
        "category": "compliance",
        "name": "Lipsa monitorizării obligațiilor fiscale",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R42",
        "category": "compliance",
        "name": "Lipsa verificărilor interne",
        "impact": 4,
        "probability": 2,
    },
    {
        "code": "R43",
        "category": "compliance",
        "name": "Dependență excesivă de contabil",
        "impact": 3,
        "probability": 2,
    },
    # 8. Riscuri reputaționale (R44-R50)
    {
        "code": "R44",
        "category": "reputational",
        "name": "Expunere la controale fiscale",
        "impact": 5,
        "probability": 2,
    },
    {
        "code": "R45",
        "category": "reputational",
        "name": "Istoric fiscal negativ",
        "impact": 5,
        "probability": 2,
    },
    {
        "code": "R46",
        "category": "reputational",
        "name": "Parteneri cu risc fiscal",
        "impact": 5,
        "probability": 2,
    },
    {
        "code": "R47",
        "category": "reputational",
        "name": "Structuri economice greu justificabile",
        "impact": 5,
        "probability": 2,
    },
    {
        "code": "R48",
        "category": "reputational",
        "name": "Parteneri cu istoric financiar incert",
        "impact": 5,
        "probability": 2,
    },
    {
        "code": "R49",
        "category": "reputational",
        "name": "Afectarea imaginii profesionale",
        "impact": 5,
        "probability": 2,
    },
    {
        "code": "R50",
        "category": "reputational",
        "name": "Lipsa verificării partenerilor comerciali",
        "impact": 4,
        "probability": 2,
    },
]

RESPONSABIL_COEF = {"administrator": 0.8, "delegat": 1.0, "contabil": 1.3}

RISK_LEVEL_THRESHOLDS = [(10, "LOW"), (20, "MEDIUM"), (35, "HIGH"), (50, "CRITICAL")]

TARIFF_ADJUSTMENT = {"LOW": 0, "MEDIUM": 10, "HIGH": 25, "CRITICAL": 50}
